### ISSUE TITLE
Set up boards and pages in Github for documentation, work tracking and guidelines

### ISSUE THREAD

**Issue by ThomasWomack** [cfa-nm/ABQCRG#1]
- [x] Create repository
- [x] Create issue board
- [x] Upload plan to wiki
- [x] Create and upload guidelines wiki

Expected Finish 2/23
